In [1]:
import numpy

In [2]:
numpy.__version__

'1.20.1'

In [3]:
import numpy as np

# Array

In [4]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [5]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [7]:
a[0]

array([1, 2, 3, 4])

In [8]:
a[1]

array([5, 6, 7, 8])

In [10]:
a[-1]

array([ 9, 10, 11, 12])

In [11]:
#bentuk array adalah bilangan bulat non-negatif dan datanya bersfat homogen

In [16]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [18]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [20]:
np.empty(6)

#np.empty tergantung kepada data terakhir yg kita input

array([1., 1., 1., 1., 1., 1.])

In [22]:
np.arange(4)

array([0, 1, 2, 3])

In [24]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [27]:
np.arange(2,29,5)

#(start,stop,step)

array([ 2,  7, 12, 17, 22, 27])

# Add, Remove and Sort

In [30]:
arr = np.array([1,2,3,4,5,6,7,8])

In [31]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [35]:
np.append(arr,[1.2])

#0,1,2,3,4,5,6,7

array([1. , 2. , 3. , 4. , 5. , 6. , 7. , 8. , 1.2])

In [36]:
np.delete(arr,1)

array([1, 3, 4, 5, 6, 7, 8])

In [37]:
arr = np.array([2,1,5,3,7,4,6,8])

In [38]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [39]:
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

# Shape & Size

In [43]:
array_example = np.array([[[0,1,2,3],
                           [4,5,6,7]],
                           
                           [[0,1,2,3],
                            [4,5,6,7]],
                           
                           [[0,1,2,3],
                            [4,5,6,7]]])

In [44]:
print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [45]:
array_example.ndim

3

In [46]:
array_example.size

24

In [47]:
array_example.shape

(3, 2, 4)

In [49]:
arr_one = np.array([[1,2,3,4,5]])

In [53]:
arr_one.ndim

2

In [54]:
arr_one.size


5

In [55]:
arr_one.shape

(1, 5)

# Reshape

In [57]:
a = np.arange(6)

In [58]:
a

array([0, 1, 2, 3, 4, 5])

In [59]:
a.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [60]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

# Covert 1D to 2D

In [72]:
a = np.array([1,2,3,4,5,6])

In [73]:
a.shape

(6,)

In [74]:
a2 = a[np.newaxis]

In [75]:
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [77]:
row_vector = a[np.newaxis,:]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [78]:
col_vector = a[:,np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [79]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [83]:
b = np.expand_dims(a, axis=1)
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [82]:
c = np.expand_dims (a,axis=0)
c

array([[1, 2, 3, 4, 5, 6]])

In [84]:
b.shape

(6, 1)

In [85]:
c.shape

(1, 6)

# Indexing and Slicing

In [86]:
data = np.array([1,2,3])
print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

[1 2 3]
1
2
[1 2]
[2 3]
[2 3]


In [87]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [93]:
a


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [94]:
a.shape

(3, 4)

In [95]:
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]


In [98]:
five_up = (a>=5)
a[five_up]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [99]:
a[a>=5]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [106]:
divisible_by_2 = a[a%2==0]

#% adalah modular

In [109]:
10%5==0

True

In [110]:
10%3==0

False

In [111]:
divisible_by_2

array([ 2,  4,  6,  8, 10, 12])

In [117]:
c=a[(a>2)&(a<11)]
print(c)


c=a[(a>2)|(a<11)]
print(c)


[ 3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [114]:
# and (&)
# or (|)

# Creating Array From Existing Data

In [120]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

In [122]:
arr1 = arr [3:8]
arr1

array([4, 5, 6, 7, 8])

In [124]:
a_1 = np.array([[1,1],
      [2,2]])

In [125]:
a_2 = np.array([[3,3],
      [4,4]])

In [126]:
np.vstack((a_1,a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [127]:
np.hstack((a_1,a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [128]:
arrsplit = np.array([[1,2,3,4,5,6,7,8,9,10,11,12],
                   [13,14,15,16,17,18,19,20,21,22,23,24]])
print(arrsplit)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [129]:
np.hsplit(arrsplit,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [150]:
x, y, z = np.hsplit(arrsplit,3)

In [151]:
x

array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]])

In [152]:
y

array([[ 5,  6,  7,  8],
       [17, 18, 19, 20]])

In [153]:
z

array([[ 9, 10, 11, 12],
       [21, 22, 23, 24]])

In [130]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [134]:
b = a.view()
b

#new object same data

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [136]:
c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# Basic Array Operations

In [137]:
a = np.array ([1,2,3,4])
a.sum()

10

In [142]:
b = np.array ([[1,1],[2,2]])
b

array([[1, 1],
       [2, 2]])

In [145]:
b.sum(axis=0)

#pertambahan vertical

array([3, 3])

In [146]:
b.sum(axis=1)

#pertambahan horizontal

array([2, 4])

In [147]:
data = np.array([1,2])
data

array([1, 2])

In [155]:
ones = np.ones(2)
ones

array([1., 1.])

In [156]:
data + ones

array([2., 3.])

In [159]:
data - ones

array([0., 1.])

In [157]:
data*data

array([1, 4])

In [158]:
data/data

array([1., 1.])

# Broadcasting

In [160]:
data*2

array([2, 4])

# More Array Operations

In [161]:
A = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
             [0.54627315, 0.05093587, 0.40067661, 0.556455993],
             [0.12697628, 0.82485143, 0.26590556, 0.5617101]])
print(A)

[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645599]
 [0.12697628 0.82485143 0.26590556 0.5617101 ]]


In [162]:
A.sum()

4.852113553000001

In [163]:
A.min()

0.05093587

In [181]:
A.min(axis=0)

#axis0 scanning ke kanan atau horizontal nilai minum/maxnya berapa

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [168]:
A.max()

0.82485143

In [179]:
A.max(axis=1)

array([0.5510652 , 0.55645599, 0.82485143])

In [171]:
A.std()

0.2134531508300109

In [173]:
A.prod(axis=0)

array([0.03125066, 0.00726716, 0.03662519, 0.17224477])

# Matrices

# Creating Matrices

In [185]:
A

array([[0.45053314, 0.17296777, 0.34376245, 0.5510652 ],
       [0.54627315, 0.05093587, 0.40067661, 0.55645599],
       [0.12697628, 0.82485143, 0.26590556, 0.5617101 ]])

In [195]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [196]:
np.zeros((3,2))


array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [197]:
np.random.random((3,2))

array([[0.77204302, 0.19247798],
       [0.10682964, 0.45639762],
       [0.4092627 , 0.81455843]])

In [198]:
print(np.ones((3,2)))


[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [199]:
print(np.zeros((3,2)))


[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [200]:
print(np.random.random((3,2)))

[[0.52382522 0.42968148]
 [0.19110055 0.54009224]
 [0.31218773 0.21828202]]


# Matrix Arithmetic

In [188]:
data = np.array([[1,2],[3,4]])
print(data)

[[1 2]
 [3 4]]


In [190]:
ones = np.ones ([2,2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [191]:
print(data+ones)

[[2. 3.]
 [4. 5.]]


In [192]:
ones_row = np.ones([1,2])
print(ones_row)

[[1. 1.]]


In [194]:
print(data + ones_row)

[[2. 3.]
 [4. 5.]]


# Dot Product

In [225]:
#perkalian antar matrix

In [226]:
a_1 = np.array([[1,2,3],[4,5,6]])
print(a_1)


print(a_1.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [256]:
a_2 = np.array([[7,8],[9,10],[11,12]])
print(a_2)

print(a_2.shape)

[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [257]:
a_1

array([[1, 2, 3],
       [4, 5, 6]])

In [258]:
a_2

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [259]:
np.dot(a_1,a_2)

array([[ 58,  64],
       [139, 154]])

# Matrix Indexing

In [230]:
data = np.array([[1,2],[3,4],[5,6]])
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [231]:
print(data[0])

[1 2]


In [232]:
print(data[1])
print(data[2])

[3 4]
[5 6]


In [239]:
print(data[0,1])

#(row,kolom ke)

2


In [234]:
print(data[1:3])


[[3 4]
 [5 6]]


In [235]:
print(data[0:2,1])

[2 4]


# Matrix Aggregation

In [240]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [242]:
data.max()

6

In [243]:
data.min()

1

In [244]:
data.sum()

21

In [245]:
data.max(axis=0)

array([5, 6])

In [246]:
data.max(axis=1)

array([2, 4, 6])

# Transposing & Reshaping

In [247]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [250]:
data.T

#T = transpost

array([[1, 3, 5],
       [2, 4, 6]])

In [252]:
data_col = np.array([[1,2,3,4,5,6]]).T
data_col

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [253]:
data_col.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [254]:
data_col.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [263]:
arr = np.arange(6).reshape((2,3))
print(arr)


[[0 1 2]
 [3 4 5]]


# N-Dimensional Array

In [260]:
ndarr = np.array([[[1,2],[3,4]],
                 [[5,6],[7,8]]])
print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [269]:
print(np.ones((4,3,2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [265]:
print(np.zeros((4,3,2)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [270]:
print(np.random.random((4,3,2)))

[[[0.40798568 0.28744861]
  [0.11368682 0.2641217 ]
  [0.64515812 0.28615302]]

 [[0.44255306 0.11189212]
  [0.0582517  0.29515838]
  [0.43049695 0.27912258]]

 [[0.84848545 0.11723316]
  [0.4838145  0.96969217]
  [0.39055113 0.60154517]]

 [[0.18645749 0.24888657]
  [0.9238234  0.98718168]
  [0.42207602 0.48647231]]]


# Flatten N-Dimensional Array

In [281]:
arrflat = np.array ([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [282]:
arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [284]:
x = arrflat.ravel()
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


# Working with Math Formula

In [285]:
#error = (1/n)*np.sum(np.square(observed-prediction))

In [286]:
observed = np.random.random((3,2))
prediction = np.random.random((3,2))

In [287]:
observed

array([[0.73173966, 0.32119937],
       [0.08302385, 0.70814365],
       [0.85842811, 0.29290174]])

In [288]:
prediction

array([[0.16652106, 0.60394779],
       [0.93937377, 0.76771562],
       [0.25158874, 0.87393984]])

In [292]:
observed.size 

6

In [293]:
(1/observed.size)*np.sum(np.square(observed - prediction))

0.3070270062174241

In [294]:
n = observed.size 

error = (1/n)*np.sum(np.square(observed-prediction))

In [295]:
error

0.3070270062174241